.travis.yml, requirements.txt, sklearn_keras_wrap/wrappers.py, tests/test_wrappers.py
- Restructure wrapper to fully support Scikit-Learn API
- Deprecate Python 2 since this is now an external package
- Move tests to Pytest
=> Restructure wrapper to fully support Scikit-Learn API

sklearn_keras_wrap/wrappers.py, tests/test_wrappers.py
Opening to document for future.
Ultimately, I think these wrappers should be able to pass the exhaustive tests in `sklearn.utils.estimator_checks.check_estimator`. In fact, these tests cover a lot of the testing that is currently being done and more.
All of the tests that are currently failing are related to random states. It is my understanding that there is no easy way to set the random state of TF/Keras. The Scikit-Learn tag API defines a parameter `non_deterministic` that if set to `True` I think should make these tests xpass, but it doesn't seem to be checked currently, the tags API is pretty new. More info on tags [here](https://scikit-learn.org/stable/developers/develop.html).
These are the tests that were added:
```python3
def dynamic_classifier(X, cls_type_, n_classes_, …
```
=> Add extensive tests from scikit-learn test suite

sklearn_keras_wrap/wrappers.py, tests/test_wrappers.py
Fixes #4 
This adds a violation of the Scikit-Learn API: if `build_fn` is a prebuilt model, it is modified before saving. `Model` instances cannot be pickled directly and hence cannot be saved as an attribute in `__init__`, which is what the Scikit-Learn API expects.
=> BUG: Fix packing/unpacking of prebuilt model build_fn attribute

tests/test_wrappers.py
The scikit-learn estimator tests broke in the latest release. They were being xFailed/xPassed anyway, so I am going to disable for now to unblock other more important stuff.
=> FIX: Disable tests imported from scikit-learn

sklearn_keras_wrap/wrappers.py, tests/test_wrappers.py
This PR changes to using sklearn OneHotEncoder and LabelEncoder to handle label encoding for categorical_crossentropy vs binary_crossentropy. Previously, encoding was being done manually using numpy. This closes #12
=> Use sklearn transformers for label manipulation

scikeras/wrappers.py, tests/test_wrappers.py
From testing in #39 I learned that future versions of Scikit-Learn are introducing a new test for the `sample_weight` parameter.
It seems that because of how Keras applies the `sample_weight` parameter, a value of `0` doesn't result in the sample being completely ignored.
This PR adds a manual step where any `sample_weight` values of exactly 0 result in those samples being deleted.
=> FIX: Update sample weight processing for future Scikit-Learn versions

scikeras/__init__.py, scikeras/_utils.py, scikeras/wrappers.py
The name of  metrics may change when a model goes through a serialize -> deserialize round trip. It is not enough to normalize the name when the model is serialized the first time, since the `history_` attribute may be initialized with keys before the first serialization.
The solution is to have a function that normalizes metric names to the full name and use that every time `history_` is updated so that `history_` has consistent keys.
This should resolve #34.
=> BUG: Normalize loss metric names

README.md, scikeras/wrappers.py, tests/test_wrappers.py
As per suggestion in https://github.com/adriangb/scikeras/issues/37#issuecomment-671636894, this makes these functions public and removes the extra underscore from the name.
=> REF: Rename pre/post process functions and make public

scikeras/_utils.py, scikeras/wrappers.py, tests/test_wrappers.py
It set default values of `build_fn` to be model parameters. This means model selection searches mirror the Scikit-learn interface.
This PR makes this search possible:
``` python
def build_fn(solver="sgd"):
...
model.compile(optimizer="sgd", ...)
return model
params = {"solver": ["sgd", "adam"]}
model = wrappers.KerasClassifier(build_fn, epochs=2)
assert "solver" in model.get_params()
search = GridSearchCV(model, params)
search.fit(*mnist())
```
This almost exactly mirrors this Scikit-learn example:
``` python
from sklearn.datasets import make_classification
from sklearn.model_selection import GridSearchCV
from sklearn.neural_network import MLPClassifier
X, y = make_classification()
params = {"solver": ["sgd", "adam"]}
model = MLPClassifier(max_iter=2) …
```
=> ENH: set build_fn default values as model parameters

scikeras/_utils.py, scikeras/wrappers.py, tests/test_wrappers.py
This implements hardcoding of common Keras parameters in `BaseWrapper.__init__` as discussed in #37.
The parameters chosen come from `Model.compile`, `Model.predict` and `Model.fit`. Parameters were not hardcoded if:
- They don't make sense for Scikit-Learn/Numpy arrays (for example, `steps_per_epoch`).
- Should be fed to `fit` directly because they depend on the data (ex: `sample_weights`, `class_weights`). I think `validation_data` also falls into this category, but I am not sure if this makes much sense to implement since AFAIK this is not used anywhere else in Scikit-Learn. I am going to leave this for another PR where I'll also deprectate `fit`'s `**kwargs`.
=> REF: Hardcode Keras params

scikeras/wrappers.py, tests/test_wrappers.py
=> ENH: Implement run_eagerly parameter

scikeras/wrappers.py, tests/test_input_outputs.py
As per:
- https://github.com/adriangb/scikeras/pull/59#discussion_r471756149
- https://github.com/adriangb/scikeras/pull/59#discussion_r471768197
@stsievert let me know if there's anything else you catch from #59 . I should have waited for you to merge, sorry about that!
=> MAINT: fix needless ndarray creation

scikeras/wrappers.py, tests/test_compile_kwargs.py, tests/test_errors.py
As discussed in several previous issues. Checks off a task on #79.
This does not break any APIs because it does not check the `__init__` param. Instead it directly checks `tf.keras.Model.loss` after the user returns control over to SciKeras.
=> ENH: user friendly error if there is no loss function

tests/test_scikit_learn_checks.py
Fix failures in `check_methods_sample_order_invariance`. This seems to improve reliability, but possibly may not be 100% still.
=> MAINT/TST: stabilize new sklearn tests

scikeras/wrappers.py, tests/test_api.py, tests/test_callbacks.py, tests/test_errors.py, tests/test_input_outputs.py, tests/test_param_routing.py, tests/test_parameters.py, tests/test_scikit_learn_checks.py, tests/test_serialization.py
=> MAINT: rename build_fn to model in tests

scikeras/utils/__init__.py, scikeras/wrappers.py, tests/test_utils.py
It simplifies the logic behind `loss_name` and `metric_name`. Now, the following are implemented:
* `loss_name` and `metric_name` always return a string in snake case. This means that `loss_name(tf.keras.losses.CategoricalCrossentropy) == loss_name("categorical_crossentropy")`.
* The tests are split up to test one thing at a time.
**Reference issues/PRs**
This comes from this thread: https://github.com/adriangb/scikeras/pull/88#discussion_r502819242.
=> MAINT: simplify loss_name and metric_name logic

scikeras/utils/__init__.py, scikeras/wrappers.py, tests/test_input_outputs.py
It's a follow up on #102. It incorporates those changes into `wrappers.py`. Specifically, simplifies the logic in that file and removes the unnecessary try/except blocks.
It also renames an error from RuntimeError to ValueError, the proper error because an array of the wrong shape is passed, and adds some more information to other error messages.
=> MAINT: simplify logic in wrappers.py from #102

scikeras/wrappers.py, tests/test_param_routing.py
Closes #107.
`_model_params` was added in #67, but is never used in SciKeras. It could have been used within `BaseWrapper._build_keras_model`, but that same PR implements `route_params` which is used instead and is much more flexible. In fact, the code implemented in `_build_keras_model`: https://github.com/adriangb/scikeras/blob/9f633f5c21a45b43986a8d779c3ef9e3005038bb/scikeras/wrappers.py#L300-L305
Ends up being the same thing as `_model_params`:
https://github.com/adriangb/scikeras/blob/9f633f5c21a45b43986a8d779c3ef9e3005038bb/scikeras/wrappers.py#L188-L195
I think that we should delete this method/property, and that is what is being proposed in this PR.
=> MAINT: Remove _model_params property

scikeras/wrappers.py, tests/test_api.py, tests/test_input_outputs.py
This PR adds logic to correctly increment epochs when using partial fit. This will allow learning rate schedulers and other epoch dependent functionality to correctly track the epochs.
=> MAINT: Epochs increment

scikeras/utils/transformers.py, scikeras/wrappers.py, tests/test_api.py, tests/test_parameters.py
Overrides `initialize` in `KerasClassifier` to properly handle the `classes` param of `partial_fit`.
=> BUG: fix the initialize method for KerasClassifier

.github/workflows/tests.yaml
The latests sklearn nightly seems to specify scipy>=19... The latest version of scipy is 15. This PR allows other tests to keep running when nightly tests fail, but still marks the nightly as failed.
=> TST: allow tests to continue if dev tests fail

scikeras/wrappers.py, tests/test_deprecation.py
Because `epoch` was a hardcoded parameter to `_fit` when called from `fit`, it could not be passes within `fit`'s `**kwargs`. As long as we are allowing `**kwargs`, there is no reason for `epochs` alone to fail.
=> BUG: ensure epochs can be passes as a **kwarg to fit

scikeras/__init__.py, scikeras/_saving_utils.py, scikeras/_utils.py, scikeras/wrappers.py, tests/mlp_models.py, tests/test_api.py, tests/test_serialization.py
Building upon the test added in #126.
This PR implements:
1. `SaveModel` based serialization.
2. General serialization for optimizers, metrics and losses.
3. Tests for serializing optimizers, metrics and losses.
Closes #126, closes #70, closes #125
=> MAINT/ENH: SaveModel based serialization

scikeras/wrappers.py
=> MAINT: fix signature of BaseWrapper.scorer

scikeras/wrappers.py
I believe the test that was failing here was resolved in https://github.com/adriangb/scikeras/pull/152.
In hindsight, I think the original issue was that 1 epoch of training probably wasn't enough to see the effect of sample_weight in the way the test is looking for.
=> MAINT: remove unecessary sample_weight logic

.github/workflows/deploy_docs.yml, .github/workflows/docs.yaml
As evidenced by #176 , docs can't be deployed from a fork, for security reasons.
The workaround is to have 2 workflows: one to build, one to deploy.
The build workflow is run from the fork (i.e. the PR author can edit this workflow to their hearts content) and the only expectation is that a folder with HTML stuff is published.
The deploy workflow is run from master. The security concern is alleviated because PR authors can't use workflows to push code without review. This workflow will never be runnable from the PR that is updating it, but luckily it shouldn't need to be updated very often.
=> BUG: docs can't be built from forks

poetry.lock, pyproject.toml, scikeras/__init__.py
- Add coverage source to pyproject.toml to avoid running coverage on venv/.venv.
- Use caret versioning instead of >=
- Use pyproject.toml as the single source of version truth.
=> MAINT: toml & dep fixes

pyproject.toml, scikeras/__init__.py
=> MAINT: add importlib-metadata dep for python <3.8

.gitignore
This reduces the number of named things that we don't use by excluding everything except the project files.
This also avoids accidentally committing test files and such at the repo root.
=> MAINT: better .gitignore

.github/workflows/tests.yaml
See thread in https://github.com/adriangb/scikeras/pull/208#pullrequestreview-601401430
Since we use GHA as a FOSS project, we really don't pay for usage. This will increase usage because tests will run even if linting fails, but will help PR feedback TAT because failed linting won't preclude getting test data back.
=> MAINT: remove test dependance on linting

docs/source/migration.rst, pyproject.toml
=> DOC: Add history attribute to migration

pyproject.toml
This fixes incorrect dependency specification which was causing sklearn to be stuck at `0.22.0`.
=> Fix dependency specification

.github/workflows/tests.yaml, pyproject.toml, scikeras/__init__.py
=> Remove hard dependency on TensorFlow

scikeras/wrappers.py, tests/test_parameters.py
=> Remove deprecation warning for **kwargs and support them in partial_fit

.github/workflows/tests.yaml, docs/source/install.rst, pyproject.toml, scikeras/_utils.py, scikeras/utils/transformers.py, scikeras/wrappers.py, tests/test_api.py, tests/test_input_outputs.py, tests/test_scoring.py
- Replace `tf.python.keras` imports with `tf.keras` imports
- Clean up string -> class conversion for optimizers, losses and metrics
- Remove pytest-xdist since it seems that random state configuration is no longer compatible with multiprocess execution of tests (evidenced by fragility in training results)
=> MAINT: Fix keras imports on tf-nightly after the keras/tf repo split

scikeras/wrappers.py, tests/test_parameters.py
Fixes use of `class_weight` parameter.
Currently, the `class_weight` parameter passed to the `KerasClassifier` constructor gets passed to Keras, which breaks `class_weight="balanced"` and any other values that are supported by Scikit-Learn (which we want to support in SciKeras) but no in Keras.
=> Fix handling of class_weight=balanced

.github/workflows/tests.yaml, README.md, docs/source/install.rst, docs/source/notebooks/Benchmarks.md, pyproject.toml, scikeras/__init__.py, scikeras/_saving_utils.py, scikeras/_utils.py, scikeras/wrappers.py, tests/__init__.py, tests/multi_output_models.py, tests/test_api.py, tests/test_errors.py, tests/test_input_outputs.py, tests/test_parameters.py, tests/test_scikit_learn_checks.py, tests/test_serialization.py, tests/testing_utils.py
This fixes compatibility with TensorFlow 2.7.0, at the cost of dropping support for older versions.
=> BREAKING CHANGE: bump TensorFlow dependency to 2.7.0

.github/workflows/tests.yaml, README.md, docs/source/install.rst, docs/source/notebooks/Benchmarks.md, docs/source/notebooks/DataTransformers.md, docs/source/notebooks/Meta_Estimators.md, pyproject.toml
Fixes #261 
```
poetry add --optional tensorflow==2.7.0
poetry add --optional tensorflow==2.7.0
```
Update documentation. I updated all pip install sites - but maybe only some need to be updated?
=> MAINT: add optional packages for tensorflow and tensorflow-cpu; update documentation

scikeras/wrappers.py
Sklearn interface presumes the estimators inherit from RegressorMixin and ClassifierMixin. It doesn't accually add any useful functionality, but it allows one to check, what interface do the class implement
`isinstance(model, RegressorMixin)`
It is useful to check this in your code to know if e.g. the class implements predict_proba and how do predict work (give some continuous scores or discrete predictions).
=> Add sklearn mixin inheritance

scikeras/wrappers.py, tests/test_scikit_learn_checks.py, tests/test_scoring.py
- Downgrades an overly aggressive/ambitious numeric comparison
- Removes samples with sample weight = 0
=> chore/fix: compatibility with newest nightly builds

scikeras/wrappers.py, tests/test_api.py
Allow for model instantiation functions which are built using functools.partial.
I imagine this is a common use case, where model functions might need to have certain parameters set using functools.partial. In that case, inspect.function() returns False, and this extra check is required.
Thanks for the awesome package, super useful!!!
=> Allow functools.partial in wrappers.py

.github/workflows/tests.yaml, pyproject.toml, scikeras/_saving_utils.py, scikeras/utils/transformers.py, tests/__init__.py, tests/test_api.py, tests/test_compile_kwargs.py, tests/test_parameters.py, tests/test_serialization.py
There are quite a few breaking changes in 2.11.0 (mostly because we're digging deep into the Optimizer API) so to support 2.11.0 we'll have to drop support for older versions.
=> Support TensorFlow 2.11.0
