adriangb/scikeras

.pre-commit-config.yaml, README.md
=> Documentation

tests/test_wrappers.py
Parametrize tests for more verbose failures and logging.
=> Parametrize config in tests

sklearn_keras_wrap/wrappers.py
Cleanup of last merge. This way we respect the Scikit-Learn API a bit more by modifying the Keras Model input instead of converting it to another type.
=> Use __reduce_ex__ for serialization of Keras Models

sklearn_keras_wrap/wrappers.py
With the addition of `__reduce_ex__`, we can now get rid of these two functions completely.
=> Clean up __set_state__ and __get_state__.

sklearn_keras_wrap/wrappers.py, tests/test_wrappers.py
Long time in the making. This removes a lot of duplicate functionality, and should fix some yet untested compatibility issues.
=> Derive BaseWrapper from BaseEstimator

scikeras/wrappers.py, tests/test-output.xml, tests/test_wrappers.py
It implements and tests `partial_fit` for `scikeras.BaseWrapper` models. It also exposes a `warm_start` parameter in `BaseWrapper.fit`.
**Reference issues/PRs**
This will be useful for https://github.com/dask/dask-ml/issues/696.
=> ENH: implement partial_fit for SciKeras models

scikeras/wrappers.py, tests/test_wrappers.py
https://scikit-learn-enhancement-proposals.readthedocs.io/en/latest/slep010/proposal.html
=> MAINT: ScikitLearn SLEP10 compliance

README.md, requirements.txt
What does this PR implement?
Just a small update of the requirments
Reference issues/PRs
This resolves https://github.com/adriangb/scikeras/issues/32
=> Fix requirments

README.md, scikeras/wrappers.py, tests/test_wrappers.py
=> REF: Rename __call__ to _keras_build_fn for subclassed model building

README.md
Fix docs as per https://github.com/adriangb/scikeras/issues/31#issuecomment-670368822
=> Update docs, closes #31

README.md, scikeras/wrappers.py, tests/mlp_models.py, tests/test_api.py, tests/test_errors.py, tests/test_parameters.py, tests/test_scikit_learn_checks.py, tests/test_scoring.py, tests/test_serialization.py
=> Rename root_mean_squared_error -> r_squared

tests/test_input_outputs.py
Reduces tests from ~hundreds to ~dozens with largely the same coverage
=> TST: Split up tests and reduce parametrization

.github/workflows/tests.yaml
From testing, this is both faster, more reliable and less complex than having the cache.
=> MAINT/TST: remove CI cache

docs/source/conf.py, pyproject.toml, scikeras/_utils.py, scikeras/wrappers.py, tests/mlp_models.py, tests/test_api.py, tests/test_callbacks.py, tests/test_compile_kwargs.py, tests/test_errors.py, tests/test_input_outputs.py, tests/test_param_routing.py, tests/test_parameters.py, tests/test_scikit_learn_checks.py, tests/test_serialization.py, tests/testing_utils.py
It configures black to have the default line length of 88 characters instead of 79 characters.
I'm submitting this PR because I almost recommended this change multiple times in #66. I held back not to make that PR more complicated and make the diff even longer.
=> MAINT: longer line length for black

tests/test_errors.py, tests/test_parameters.py
=> MAINT: catch internal random_state warnings

scikeras/wrappers.py, tests/test_api.py, tests/test_input_outputs.py
=> Partial fit single epoch

scikeras/utils/transformers.py, scikeras/wrappers.py, tests/test_api.py
Closes #69.  Blocked by #88, will redirect destination branch to `master` after that is merged.
=> ENH: add handling of classes param in partial_fit

scikeras/utils/transformers.py, scikeras/wrappers.py, tests/test_input_outputs.py, tests/test_scikit_learn_checks.py
Also fixes handling of targets of object type in classifiers discovered by sklearn's `check_classifiers_classes` test.
=> TST: Split out unstable sklearn checks & add more training for them

scikeras/wrappers.py
=> BUG: fix typo in wrappers.py

docs/source/notebooks/Basic_Usage.md, docs/source/notebooks/DataTransformers.md, docs/source/notebooks/MLPClassifier_MLPRegressor.md, scikeras/utils/transformers.py, scikeras/wrappers.py
=> DOC: Fix doc links

scikeras/wrappers.py
Pulls common logic from predict and predict_proba into _predict_raw to reduce logic duplication and LOC to change.
=> MAINT: consolidate predict and predict_proba into _predict_raw

docs/source/notebooks/Basic_Usage.md, scikeras/wrappers.py, tests/mlp_models.py, tests/test_api.py, tests/test_errors.py, tests/test_parameters.py, tests/test_scikit_learn_checks.py, tests/test_scoring.py, tests/test_serialization.py
=> DOC/TST: Use r2 as a metric

scikeras/_saving_utils.py
- Add type hints
- Use tarfile instead of zipfile (we just want to create an archive)
=> MAINT: add type-hints to _saving_utils.py

.github/workflows/build_docs.yaml, docs/README.md, pyproject.toml
=> Move DOC dependencies to dev

pyproject.toml
=> Unblock Python version

tests/test_input_outputs.py
This is an attempt to mitigate flakey tests that sometimes weren't hitting the target scores.
=> MAINT: mitigate flakey tests

docs/source/install.rst
=> DOC: Add note on installing without dependencies

pyproject.toml
Closes https://github.com/adriangb/scikeras/issues/246
=> fix missing dependencies

scikeras/_utils.py, tests/test_param_routing.py
=> Fix routed parameter overriding

docs/source/notebooks/Benchmarks.md, pyproject.toml, scikeras/_utils.py, scikeras/utils/random_state.py, scikeras/wrappers.py, tests/test_random_state.py
=> feat: add context manager for setting TensorFlow's random generator

docs/source/migration.rst, pyproject.toml
=> doc: document that TensorFlow Datasets are not supported as inputs

README.md, docs/source/quickstart.rst
=> Fixed Some Typos in `README.md` and Documentation

.github/workflows/tests.yaml, pyproject.toml
=> Support python 3.10

.github/workflows/tests.yaml
Until https://github.com/keras-team/keras/issues/16983 gets resolved
=> Disable testing on TF nightly

.gitignore, CITATION.cff
=> Add CITATION.cff

.github/workflows/tests.yaml, pyproject.toml
This change includes the update on the pyproject.toml file. As the previous release failed due to the package version, as it was the same one that was already present in the Pypi. 
Please refer to this traceback to see the whole error: https://github.com/adriangb/scikeras/actions/runs/6383670304
=> chore: updating the poetry version to fix the push issue
